#!/bin/bash
# Spec-Kit Bridge Script
# Bridges harness Jira context to spec-kit workflow

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CACHE_DIR="${HARNESS_CACHE_DIR:-.harness/.cache}"
SPEC_DIR="${SPEC_KIT_SPEC_DIR:-.spec-kit}"
AI_AGENT="${SPEC_KIT_AI:-claude}"

ACTION="${1:-help}"

# Detect issue
ISSUE=$("$SCRIPT_DIR/detect-issue.sh" 2>/dev/null | tr -d '\n' || echo "")
ISSUE="${ISSUE:-unknown}"

JIRA_CONTEXT="$CACHE_DIR/jira-context-${ISSUE}.json"
CODE_CONTEXT="$CACHE_DIR/code-context-${ISSUE}.json"

# Ensure spec directory exists
mkdir -p "$SPEC_DIR"

# Extract Jira context into variables
extract_jira_context() {
    if [ -f "$JIRA_CONTEXT" ]; then
        ISSUE_KEY=$(jq -r '.issue.key // ""' "$JIRA_CONTEXT")
        ISSUE_SUMMARY=$(jq -r '.issue.summary // ""' "$JIRA_CONTEXT")
        ISSUE_TYPE=$(jq -r '.issue.type // "Story"' "$JIRA_CONTEXT")
        ISSUE_DESCRIPTION=$(jq -r '.issue.description // ""' "$JIRA_CONTEXT")
        ACCEPTANCE_CRITERIA=$(jq -r '.issue.acceptance_criteria | join("\n")' "$JIRA_CONTEXT" 2>/dev/null || echo "")
        EPIC_SUMMARY=$(jq -r '.epic.summary // ""' "$JIRA_CONTEXT")
        EPIC_DESCRIPTION=$(jq -r '.epic.description // ""' "$JIRA_CONTEXT")

        # Extract hierarchy (Feature/Initiative)
        FEATURE_SUMMARY=$(jq -r '.hierarchy[] | select(.type == "feature") | .summary // ""' "$JIRA_CONTEXT" 2>/dev/null | head -1)
        INITIATIVE_SUMMARY=$(jq -r '.hierarchy[] | select(.type == "initiative") | .summary // ""' "$JIRA_CONTEXT" 2>/dev/null | head -1)

        # Extract handbook documents (SDP/Proposals)
        HANDBOOK_DOC_COUNT=$(jq -r '.handbook_documents.documents | length // 0' "$JIRA_CONTEXT" 2>/dev/null || echo "0")
        if [ "$HANDBOOK_DOC_COUNT" -gt 0 ]; then
            HANDBOOK_DOCS=$(jq -r '.handbook_documents.documents[] | "### \(.title // "Document")\n**Type:** \(.type)\n**Source:** \(.source_issue)\n**URL:** \(.url)\n\n\(.content)\n"' "$JIRA_CONTEXT" 2>/dev/null || echo "")
        else
            HANDBOOK_DOCS=""
        fi
        return 0
    else
        echo "Warning: No Jira context found for $ISSUE" >&2
        return 1
    fi
}

# Extract code context
extract_code_context() {
    if [ -f "$CODE_CONTEXT" ]; then
        CODE_LANGUAGE=$(jq -r '.repository.detected_language // "unknown"' "$CODE_CONTEXT")
        CODE_FILES=$(jq -r '.changes.files[].path' "$CODE_CONTEXT" 2>/dev/null | head -20 | tr '\n' ', ' || echo "")
        return 0
    else
        CODE_LANGUAGE="unknown"
        CODE_FILES=""
        return 1
    fi
}

# Generate spec from Jira context
generate_spec() {
    echo "Generating spec for $ISSUE..."

    extract_jira_context || true
    extract_code_context || true

    SPEC_FILE="$SPEC_DIR/spec.md"

    cat > "$SPEC_FILE" << EOF
# Specification: ${ISSUE_KEY:-$ISSUE}

## Overview

**Issue:** ${ISSUE_KEY:-N/A}
**Type:** ${ISSUE_TYPE:-Story}
**Summary:** ${ISSUE_SUMMARY:-No summary available}

## Problem Statement

${ISSUE_DESCRIPTION:-No description provided. Please add context about what problem this solves.}

## Strategic Context

${INITIATIVE_SUMMARY:+**Initiative:** $INITIATIVE_SUMMARY}
${FEATURE_SUMMARY:+**Feature:** $FEATURE_SUMMARY}
${EPIC_SUMMARY:+**Epic:** $EPIC_SUMMARY}

${EPIC_DESCRIPTION:-No epic context available.}

$(if [ -n "$HANDBOOK_DOCS" ]; then
echo "## Related Documents (SDP/Proposals)"
echo ""
echo "$HANDBOOK_DOCS"
fi)

## Acceptance Criteria

${ACCEPTANCE_CRITERIA:-No acceptance criteria defined. Consider adding specific, testable criteria.}

## Functional Requirements

Based on the acceptance criteria above, the implementation must:

$(if [ -n "$ACCEPTANCE_CRITERIA" ]; then
    echo "$ACCEPTANCE_CRITERIA" | while IFS= read -r line; do
        if [ -n "$line" ]; then
            echo "- $line"
        fi
    done
else
    echo "- [ ] Define functional requirements based on story analysis"
fi)

## Non-Functional Requirements

- Performance: Response times should be acceptable for the use case
- Security: Follow security best practices
- Testing: Include unit tests for new functionality
- Documentation: Update relevant documentation

## Technical Context

- **Primary Language:** ${CODE_LANGUAGE:-To be determined}
- **Modified Files:** ${CODE_FILES:-None yet}

## Out of Scope

- Features not mentioned in acceptance criteria
- Refactoring unrelated code
- Performance optimizations beyond requirements

---

*Generated by Harness Spec-Kit Bridge*
*Issue: ${ISSUE_KEY:-$ISSUE}*
*Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)*
EOF

    echo "Spec saved to $SPEC_FILE"
}

# Generate implementation plan
generate_plan() {
    echo "Generating implementation plan..."

    extract_jira_context || true
    extract_code_context || true

    SPEC_FILE="$SPEC_DIR/spec.md"
    PLAN_FILE="$SPEC_DIR/plan.md"

    if [ ! -f "$SPEC_FILE" ]; then
        echo "Error: No spec found. Run 'make harness/spec-kit/specify' first." >&2
        exit 1
    fi

    cat > "$PLAN_FILE" << EOF
# Implementation Plan: ${ISSUE_KEY:-$ISSUE}

## Summary

This plan outlines the technical implementation for: **${ISSUE_SUMMARY:-the current story}**

## Technical Approach

### Architecture Decisions

- **Language/Framework:** ${CODE_LANGUAGE:-To be determined based on project context}
- **Pattern:** Follow existing project patterns and conventions
- **Testing Strategy:** Unit tests for new logic, integration tests for workflows

### Implementation Phases

#### Phase 1: Setup & Foundation
- Review existing codebase structure
- Identify integration points
- Set up any required dependencies

#### Phase 2: Core Implementation
- Implement primary functionality
- Add error handling
- Write unit tests

#### Phase 3: Integration
- Integrate with existing systems
- Add integration tests
- Update documentation

#### Phase 4: Validation
- Run full test suite
- Perform manual testing
- Review against acceptance criteria

## Files to Modify

Based on the current context:
$(if [ -n "$CODE_FILES" ]; then
    echo "$CODE_FILES" | tr ',' '\n' | while IFS= read -r file; do
        if [ -n "$file" ]; then
            echo "- \`$file\`"
        fi
    done
else
    echo "- To be determined during implementation"
fi)

## Dependencies

- No external dependencies required (update if needed)

## Risks & Mitigations

| Risk | Mitigation |
|------|------------|
| Breaking existing functionality | Comprehensive test coverage |
| Performance impact | Profile critical paths |
| Security concerns | Follow OWASP guidelines |

## Success Criteria

The implementation is complete when:
$(if [ -n "$ACCEPTANCE_CRITERIA" ]; then
    echo "$ACCEPTANCE_CRITERIA" | while IFS= read -r line; do
        if [ -n "$line" ]; then
            echo "- [ ] $line"
        fi
    done
else
    echo "- [ ] All acceptance criteria from Jira are met"
    echo "- [ ] Tests pass"
    echo "- [ ] Code review approved"
fi)

---

*Generated by Harness Spec-Kit Bridge*
*Issue: ${ISSUE_KEY:-$ISSUE}*
*Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)*
EOF

    echo "Plan saved to $PLAN_FILE"
}

# Generate tasks from plan
generate_tasks() {
    echo "Generating tasks..."

    extract_jira_context || true

    PLAN_FILE="$SPEC_DIR/plan.md"
    TASKS_FILE="$SPEC_DIR/tasks.md"

    if [ ! -f "$PLAN_FILE" ]; then
        echo "Error: No plan found. Run 'make harness/spec-kit/plan' first." >&2
        exit 1
    fi

    cat > "$TASKS_FILE" << EOF
# Tasks: ${ISSUE_KEY:-$ISSUE}

## Task List

### Setup Tasks
- [ ] **TASK-001:** Review spec and plan documents
- [ ] **TASK-002:** Set up development environment
- [ ] **TASK-003:** Create feature branch (if not exists)

### Implementation Tasks
$(if [ -n "$ACCEPTANCE_CRITERIA" ]; then
    TASK_NUM=4
    echo "$ACCEPTANCE_CRITERIA" | while IFS= read -r line; do
        if [ -n "$line" ]; then
            printf "- [ ] **TASK-%03d:** Implement: %s\n" "$TASK_NUM" "$line"
            TASK_NUM=$((TASK_NUM + 1))
        fi
    done
else
    echo "- [ ] **TASK-004:** Implement core functionality"
    echo "- [ ] **TASK-005:** Add error handling"
fi)

### Testing Tasks
- [ ] **TASK-100:** Write unit tests for new code
- [ ] **TASK-101:** Write integration tests
- [ ] **TASK-102:** Run full test suite
- [ ] **TASK-103:** Manual testing and validation

### Finalization Tasks
- [ ] **TASK-200:** Update documentation
- [ ] **TASK-201:** Code review
- [ ] **TASK-202:** Address review feedback
- [ ] **TASK-203:** Merge and deploy

## Task Dependencies

\`\`\`
TASK-001 → TASK-002 → TASK-003
                         ↓
              Implementation Tasks
                         ↓
                  Testing Tasks
                         ↓
               Finalization Tasks
\`\`\`

## Estimation Notes

- Setup: ~30 minutes
- Implementation: Varies based on complexity
- Testing: ~1-2 hours
- Finalization: ~1 hour

---

*Generated by Harness Spec-Kit Bridge*
*Issue: ${ISSUE_KEY:-$ISSUE}*
*Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)*
EOF

    echo "Tasks saved to $TASKS_FILE"
}

# Execute implementation
execute_implement() {
    echo "Starting implementation..."

    TASKS_FILE="$SPEC_DIR/tasks.md"

    if [ ! -f "$TASKS_FILE" ]; then
        echo "Error: No tasks found. Run 'make harness/spec-kit/tasks' first." >&2
        exit 1
    fi

    echo ""
    echo "Implementation guide:"
    echo ""
    echo "1. Review the tasks in $TASKS_FILE"
    echo "2. Use your AI assistant with the /speckit.implement command"
    echo "3. Or work through tasks manually"
    echo ""
    echo "For AI-assisted implementation, run in your AI agent:"
    echo "  /speckit.implement"
    echo ""
    echo "The agent will read the spec, plan, and tasks to guide implementation."
}

# Run full workflow
run_workflow() {
    echo "Running full spec-kit workflow..."
    echo ""

    echo "Step 1/3: Generating spec..."
    generate_spec
    echo ""

    echo "Step 2/3: Creating plan..."
    generate_plan
    echo ""

    echo "Step 3/3: Breaking down tasks..."
    generate_tasks
    echo ""

    echo "Workflow complete!"
}

# Main dispatch
case "$ACTION" in
    specify)
        generate_spec
        ;;
    plan)
        generate_plan
        ;;
    tasks)
        generate_tasks
        ;;
    implement)
        execute_implement
        ;;
    workflow)
        run_workflow
        ;;
    help|*)
        echo "Spec-Kit Bridge Script"
        echo ""
        echo "Usage: spec-kit-bridge.sh <action>"
        echo ""
        echo "Actions:"
        echo "  specify    Generate spec from Jira context"
        echo "  plan       Create implementation plan"
        echo "  tasks      Break down into tasks"
        echo "  implement  Guide implementation"
        echo "  workflow   Run full workflow"
        ;;
esac
